---
- name: config web-servers
  hosts: prdx-web761
  remote_user: ansible
  become: true
  
  tasks:
  - name: installing httpd
    yum:
      name: httpd
      state: latest

  - name: changing httpd.conf content
    replace:
      path: /etc/httpd/conf/httpd.conf
      regexp: '#ServerName www.example.com:80'
      replace: 'ServerName prdx-web761.ziyotek7.local:80'

  - #name: creating index.html
    #file:
     # path: /var/www/html/index.html
     # state: touch
     # mode: u+rw,g-r,o-r
 
  - name: adding content to index.html
    template:
      src: /ansible/roles/load-balancer/templates/index61.html
      dest: /var/www/html/index.html

  - name: start service
    service:
      name: httpd
      state: started
      enabled: true
    
- hosts: prdx-web762
  become: true
  tasks:
  - name: installing httpd
    yum:
      name: httpd
      state: latest

  - name: changing httpd.conf content
    replace:
      path: /etc/httpd/conf/httpd.conf
      regexp: '#ServerName www.example.com:80'
      replace: 'ServerName prdx-web762.ziyotek7.local:80'

  - name: adding content to index.html
    template:
      src: /ansible/roles/load-balancer/templates/index62.html
      dest: /var/www/html/index.html

  - name: start service
    service:
      name: httpd
      state: started
      enabled: true

- hosts: prdx-web763
  become: true
  tasks:
  - name: installing httpd
    yum:
      name: httpd
      state: latest

  - name: changing httpd.conf content
    replace:
      path: /etc/httpd/conf/httpd.conf
      regexp: '#ServerName www.example.com:80'
      replace: 'ServerName prdx-web763.ziyotek7.local:80'

  - name: adding content to index.html
    template:
      src: /ansible/roles/load-balancer/templates/index63.html
      dest: /var/www/html/index.html

  - name: start service
    service:
      name: httpd
      state: started
      enabled: true







#ServerName www.example.com:80   to     ServerName prdx-web701.ziyotek7.local:80
