---
- name: Copy Dir and Index/css.html files
  hosts: centos6
  remote_user: ansible
  become: yes

  tasks:
#  - name: rename existing index.html file
#    shell: mv /var/www/html/index.html /var/www/html/old.txt

  - name: copy index.html
    copy:
      src: /ansible/roles/web-servers/project-7-web/Centos6/index6.html
      dest: /var/www/html/

  - name: copy sytle.css file
    copy:
      src: /ansible/roles/web-servers/project-7-web/Centos6/style.css
      dest: /var/www/html/

  - name: restart httpd
    service:
      name: httpd
      state: restarted
