---
- hosts: localhost
  become: no
  vars_prompt:
  - name: root_pwd
    prompt: "Enter Password: "
    private: yes
    encrypt: "sha512_crypt"
    confirm: yes
    salt_size: 7
  tasks:
  - name: Change password
    user: 
      name: root
      password: "{{ root_pwd | password_hash('sha512') }}"
      update_password: always
