---
- name: Deploy to clients
  hosts: clients #hosts file
  remote_user: ansible
  become: true
  tasks:
  - name: make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
    ini_file:
      path: /etc/NetworkManager/NetworkManager.conf
      state: present
      no_extra_spaces: yes
      section: main
      option: dns
      value: none
      owner: root
      group: root
      mode: 0644
      backup: yes

  - name: deploy resolv.conf template
    template:
      src: /ansible/roles/DNS/DNS-Clients/resolv.conf.j2
      dest: /etc/resolv.conf

  - name: restart network
    service: 
      name: network
      state: restarted 
      
