---
 - name: Install package
   yum:
     name: [bind, bind-utils, ntp]
     state: latest

 - name: Named.conf
   copy:
     src: /ansible/roles/DNS-Master-Role/templates/named.conf.j2
     dest: /etc/named.conf

 - name: Create and copy flz file
   file: 
     path: /var/named/ziyotek.flz
     state: touch
     owner: root
     group: root
     mode: '0777'
 - name: copy
   copy:
     src: /ansible/roles/DNS-Master-Role/templates/flz.j2
     dest: /var/named/ziyotek.flz

 - name: Create and copy rlz file
   file:
     path: /var/named/ziyotek.rlz
     state: touch
     owner: root
     group: root
     mode: '0777'
 - name: copy2
   copy:
     src: /ansible/roles/DNS-Master-Role/templates/rlz
     dest: /var/named/ziyotek.rlz

 - name: Edit resolv file
   copy:
     src: /ansible/roles/DNS-Master-Role/templates/resolv.conf.j2
     dest: /etc/resolv.conf

 - name: Restart named
   service:
     name: named
     state: restarted

 - name: Enable named
   service:
     name: named
     enabled: yes
