---
- hosts: kuber-master
  remote_user: ansible
  become: yes
  tasks:

  - name: /etc/hosts file
    copy: src=/ansible/roles/K8S/Kube-Master/hosts.j2 dest=/etc/hosts
 
  - name: swap off
    shell: swapoff -a
 
  - name: Commenting Swap entries in /etc/fstab
    replace:
      path: /etc/fstab
      regexp: '(.*swap*)'
      replace: '#\1'

  - name: selinux off
    shell: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
    
  - name: firewall add ports (6443, 2379-2380, 10250, 10251, 10252, 10255) 
    firewalld:
      port: 6443/tcp
      permanent: yes
      state: enabled

  - firewalld:
      port: 2379-2380/tcp
      permanent: yes
      state: enabled
 
  - firewalld:
      port: 10250-10252/tcp
      permanent: yes
      state: enabled

  - firewalld:
      port: 10255/tcp
      permanent: yes
      state: enabled

  - name: create a file
    file:
      path: /etc/sysctl.d/k8s.conf
      state: touch
      mode: u=rw,g=r,o=r
 
  - name: Kernel Settings
    copy:  
      src: /ansible/roles/K8S/Kube-Master/kernel.j2
      dest: /etc/sysctl.d/k8s.conf 
 
  - name: Adding repository details in Kubernetes repo file.
    yum_repository:
      name: kubernetes
      description: kube repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled: yes
      gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Apply all changes
    shell: sysctl --system

  - name: Installing Docker 18.06
    shell: |
      yum install -y yum-utils device-mapper-persistent-data lvm2
      yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      export VERSION=18.06 && curl -sSL get.docker.com | sh 
 
  - name: Install Kubeadm
    yum:
      name:
      - kubeadm
      - kubelet
      - kubectl


  - name: Restart and enable the docker 
    systemd:
      name: docker
      state: restarted
      enabled: yes

  - name: Systemd restart and enable kube
    systemd:
      name: kubelet
      state: restarted
      enabled: yes
 
  - name: Initializing Kubernetes cluster
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address=192.168.38.25 >> token.txt 
  - name: Copying required files
    shell: |
      mkdir -p $HOME/.kube
      sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Network Add-on
    shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
