---
- name: update all packages using yum
  hosts: all
  become: yes

  tasks:
  - name: updating all
    yum: 
      name: "*"
      state: latest

  - name: restart system to newest kernel
    shell: "sleep 5 && reboot"
    async: 1
    poll: 0

  - name: wait for system to reboot
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 60   
