---
- name: DNS Master configuration
  hosts: dns-master
  remote_user: ansible
  become: yes

  tasks:
  - name: Install package
    yum:
      name: [bind, bind-utils, ntp]
      state: latest

  - name: Named.conf
    template:
      src: /ansible/roles/DNS-Master/named.conf.j2
      dest: /etc/named.conf

  - name: Create and copy flz file
    shell: touch /var/named/ziyotek.flz
    template:
      src: /ansible/roles/DNS-Master/flz.j2
      dest: /var/named/ziyotek.flz

  - name: Create and copy rlz file
    shell: touch /var/named/ziyotek.rlz
    template:
      src: /ansible/roles/DNS-Master/rlz.j2
      dest: /var/named/ziyotek.rlz

 - name: Edit resolv file
    template:
      src: /ansible/roles/DNS-Master/resolv.conf.j2
      dest: /etc/resolv.conf

  - name: Restart named
    service:
      name: named
      state: restarted

  - name: Enable named
    service:
      name: named
      enabled: yes

  - name: Firewall stop and disable
    shell: systemctl stop firewalld.service
    shell: systemctl disable firewalld.service
