---
- name: Install NFS-server
  hosts: nfs-server
  user: root
  become: true
  
  tasks:
    - name: Install packages
      yum: 
        name: ['nfs-utils', 'libnfsidmap']
        state: latest
    
    - name: start service rpcbind
      service:
        name: rpcbind
        state: started
        enabled: true
    

    - name: create /share directory with permissions
      file:
        path: /share
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: adding content to /etc/exports file
      lineinfile:
        path: /etc/exports
        line: /share *(rw,sync,no_root_squash)
        create: yes
  
    - name: updating export file
      shell: exportfs -r



